server:
  port: 2222
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20 #租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 60 #租期到期时间（默认90秒）
  client:
    healthcheck:
      enabled: true #开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/


# datasource
spring:
  datasource:
    url: jdbc:mysql://35.220.222.101:3306/zjp_employee?useUnicode=yes&characterEncoding=UTF-8
    username: ENC(1E01WYZE8d+w7kWB0VOm5Q==)
    password: ENC(ENomjjhuKHlpdNh8YwjceQ==)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  #none
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true

# jasypt 加密所需的salt(盐)
jasypt:
  encryptor:
    password: caspar_du

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"