server:
  port: 2222
spring:
  application:
    name: employee-service
  profiles:
    active: uat

#admin client config
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"