spring:
  application:
    name: employee-service
  profiles:
    active: dev

#admin client config
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"