server:
  port: 2222

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20 #租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 60 #租期到期时间（默认90秒）
    instance-id: 127.0.0.1:2222
    ip-address: 127.0.0.1    # 使用docker部署时 指定此实例的ip
    prefer-ip-address: true    # 注册时使用ip而不是主机名
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: false #开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
#      defaultZone: http://eureka:eureka@localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka

#feign:
#  hystrix:
#    enabled: true

# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dyc_employee?useUnicode=yes&characterEncoding=UTF-8
    username: ENC(gPWdHfd699ibTRIhxWzSTw==)
    password: ENC(gPWdHfd699ibTRIhxWzSTw==)
#    username: ENC(1E01WYZE8d+w7kWB0VOm5Q==)   #dyc
#    password: ENC(ENomjjhuKHlpdNh8YwjceQ==)   #123456
#    password: ENC(gPWdHfd699ibTRIhxWzSTw==)   #root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  #none
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true

# jasypt 加密所需的salt(盐)
jasypt:
  encryptor:
    password: caspar_du

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"